# GitHub Sponsors
github: [your-username]

# Open Collective
open_collective: react-llm

# Ko-fi
ko_fi: reactllm

# Buy Me a Coffee
custom: ["https://buymeacoffee.com/reactllm", "https://paypal.me/reactllm"]