name: Bug Report
description: Create a report to help us improve React LLM
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: React LLM version
      placeholder: ex. 1.0.0
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Arc
        - Brave
        - Other
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: ex. macOS 14.0, Windows 11, Ubuntu 22.04
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation method
      options:
        - Script tag
        - NPM package
        - Browser extension
        - Framework plugin (Next.js)
        - Framework plugin (Vite)
        - Other
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your React LLM configuration (remove any API keys)
      render: javascript
      placeholder: |
        ReactLLM.init({
          providers: {
            openrouter: "sk-or-..."
          },
          mode: "development"
        });

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including screenshots if applicable.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true